name: Build macOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build macOS app with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --windowed --name Timer main.py
        
    - name: Zip the .app (Required to preserve Mac file structure)
      run: |
        cd dist
        zip -r RadiologistTimer-macOS.zip Timer.app
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RadiologistTimer-macOS
        path: dist/RadiologistTimer-macOS.zip
